// ===== ekan 桥 shim (drpy0 环境下复刻易看Pro的全局桥) =====
// 依赖 drpy0 提供: req(url, opts)->{content}, Crypto(经 cat.js 导入)
var __ek_ext = (typeof ext !== 'undefined' && ext) ? ext : {};
var ext = __ek_ext;   // 源里 typeof ext 检查在 eval 期即成立, init() 时原地更新属性
function __ekOpts(o) {
    o = o || {};
    var opt = { headers: o.headers || {}, timeout: o.timeout || 20000 };
    return opt;
}
function request(u, o) {
    var r = req(u, __ekOpts(typeof o === 'string' ? JSON.parse(o) : o));
    return (r && r.content != null) ? r.content : r;
}
function post(u, b, o) {
    var opt = __ekOpts(typeof o === 'string' ? JSON.parse(o) : o);
    opt.method = 'POST';
    opt.data = b == null ? '' : String(b);
    opt.postType = 'raw';
    var r = req(u, opt);
    return (r && r.content != null) ? r.content : r;
}
function parseJson(s) { return JSON.parse(s); }
function encodeUri(v) { return encodeURIComponent(String(v)); }
function decodeUri(v) { return decodeURIComponent(String(v)); }
function base64Encode(v) { return Crypto.enc.Base64.stringify(Crypto.enc.Utf8.parse(String(v))); }
function base64Decode(v) { return Crypto.enc.Utf8.stringify(Crypto.enc.Base64.parse(String(v))); }
function md5(v) { return Crypto.MD5(String(v)).toString(); }
function sha1(v) { return Crypto.SHA1(String(v)).toString(); }
var __ekStore = {};
function getItem(k, d) { return (k in __ekStore) ? __ekStore[k] : (d == null ? '' : d); }
function setItem(k, v) { __ekStore[k] = String(v); }
var crypto = {
    hash: function (n, v, o) {
        o = o || {};
        var h = (n === 'SHA-1') ? Crypto.SHA1 : (n === 'SHA-256' ? Crypto.SHA256 : Crypto.MD5);
        var msg = (o.input === 'hex') ? Crypto.enc.Hex.parse(String(v)) : Crypto.enc.Utf8.parse(String(v));
        var out = h(msg);
        return (o.output === 'bytes') ? out : out.toString();
    },
    base64: {
        encode: function (v, o) { o = o || {}; var w = (o.input === 'hex') ? Crypto.enc.Hex.parse(String(v)) : Crypto.enc.Utf8.parse(String(v)); return Crypto.enc.Base64.stringify(w); },
        decode: function (v, o) { o = o || {}; var w = Crypto.enc.Base64.parse(String(v)); return (o.output === 'hex') ? Crypto.enc.Hex.stringify(w) : ((o.output === 'bytes') ? w : Crypto.enc.Utf8.stringify(w)); }
    },
    aes: {
        decrypt: function (str, key, o) {
            o = o || {};
            var k = (o.keyFormat === 'hex') ? Crypto.enc.Hex.parse(String(key)) : Crypto.enc.Utf8.parse(String(key));
            var mode = (String(o.mode || 'CBC').toUpperCase() === 'ECB') ? Crypto.mode.ECB : Crypto.mode.CBC;
            var pad = (String(o.padding || 'PKCS7').toUpperCase() === 'NoPadding') ? Crypto.pad.NoPadding : Crypto.pad.Pkcs7;
            var opt = { mode: mode, padding: pad };
            if (o.iv) opt.iv = (o.ivFormat === 'hex') ? Crypto.enc.Hex.parse(String(o.iv)) : Crypto.enc.Utf8.parse(String(o.iv));
            var msg = (o.input === 'hex') ? Crypto.enc.Hex.parse(String(str)) : null;
            var out = msg ? Crypto.AES.decrypt({ ciphertext: msg }, k, opt) : Crypto.AES.decrypt(String(str), k, opt);
            return (o.output === 'bytes') ? out : out.toString(Crypto.enc.Utf8);
        },
        encrypt: function (str, key, o) {
            o = o || {};
            var k = (o.keyFormat === 'hex') ? Crypto.enc.Hex.parse(String(key)) : Crypto.enc.Utf8.parse(String(key));
            var mode = (String(o.mode || 'CBC').toUpperCase() === 'ECB') ? Crypto.mode.ECB : Crypto.mode.CBC;
            var pad = (String(o.padding || 'PKCS7').toUpperCase() === 'NoPadding') ? Crypto.pad.NoPadding : Crypto.pad.Pkcs7;
            var opt = { mode: mode, padding: pad };
            if (o.iv) opt.iv = (o.ivFormat === 'hex') ? Crypto.enc.Hex.parse(String(o.iv)) : Crypto.enc.Utf8.parse(String(o.iv));
            var out = Crypto.AES.encrypt(String(str), k, opt);
            if (o.output === 'hex') return Crypto.enc.Hex.stringify(out.ciphertext);
            if (o.output === 'bytes') return out.ciphertext;
            return out.toString();
        }
    }
};
// ===== shim 结束 =====
/*
 * 荐片 - fish.json -> Lanerc QuickJS source
 * adapter=jianpian, site=jianpian, animeOnly=false
 * Generated by tools/generate_fish_sources.js. Do not edit generated copies directly.
 */

var SOURCE_NAME = '荐片';
var ADAPTER = 'jianpian';
var SITE_CODE = 'jianpian';
var ANIME_ONLY = false;
var BRIDGE_URL = '';
var TIMEOUT = 60000;
var SDK_INT = 36;

function text(value) { return value == null ? '' : String(value); }
function trim(value) { return text(value).replace(/^\s+|\s+$/g, ''); }
function clean(value) {
    return trim(text(value)
        .replace(/<[^>]+>/g, '')
        .replace(/&nbsp;|&#160;/gi, ' ')
        .replace(/&amp;/gi, '&')
        .replace(/&quot;/gi, '"')
        .replace(/&#0?39;|&#x27;/gi, "'")
        .replace(/&lt;/gi, '<').replace(/&gt;/gi, '>'));
}
function parse(value) {
    if (value && typeof value === 'object') return value;
    try { if (typeof parseJson === 'function') return parseJson(text(value)); } catch (ignore1) {}
    try { return JSON.parse(text(value)); } catch (ignore2) { return null; }
}
function extObject() {
    try {
        if (typeof ext === 'undefined' || ext == null) return {};
        return typeof ext === 'object' ? ext : (parse(ext) || {});
    } catch (ignore) { return {}; }
}
function cfg(key, fallback) {
    var value = extObject()[key];
    return value == null || text(value) === '' ? fallback : value;
}
function encode(value) {
    try { if (typeof encodeUri === 'function') return text(encodeUri(text(value))); } catch (ignore1) {}
    try { return encodeURIComponent(text(value)); } catch (ignore2) { return text(value); }
}
function responseText(value) {
    if (value == null) return '';
    if (typeof value === 'string') return value;
    if (value.body != null) return text(value.body);
    if (value.content != null) return text(value.content);
    try { return JSON.stringify(value); } catch (ignore) { return text(value); }
}
function getRaw(url, headers) {
    try {
        return responseText(request(text(url), JSON.stringify({ headers: headers || {}, timeout: TIMEOUT })));
    } catch (ignore) {}
    return '';
}
function postRaw(url, body, headers) {
    try {
        return responseText(post(text(url), text(body), JSON.stringify({
            headers: headers || {}, timeout: TIMEOUT
        })));
    } catch (ignore) { return ''; }
}
function b64Encode(value) {
    try { if (typeof base64Encode === 'function') return text(base64Encode(text(value))); } catch (ignore1) {}
    try { return text(crypto.base64.encode(text(value), { input: 'utf8' })); } catch (ignore2) { return ''; }
}
function b64Decode(value) {
    try { if (typeof base64Decode === 'function') return text(base64Decode(text(value))); } catch (ignore1) {}
    try { return text(crypto.base64.decode(text(value), { output: 'utf8' })); } catch (ignore2) { return ''; }
}
function randomHex(bytes) {
    try { return text(crypto.randomHex(bytes)); } catch (ignore) {}
    var out = '';
    while (out.length < bytes * 2) out += Math.floor(Math.random() * 16).toString(16);
    return out;
}
function persistentId(key) {
    var value = '';
    try { value = text(getItem(key, '')); } catch (ignore1) {}
    if (!/^[0-9a-f]{16}$/i.test(value)) {
        value = randomHex(8);
        try { setItem(key, value); } catch (ignore2) {}
    }
    return value;
}
function unique(items, limit) {
    var out = [], seen = {};
    for (var i = 0; i < (items || []).length && out.length < (limit || 9999); i++) {
        var item = items[i] || {};
        var key = text(item.id);
        if (!key || seen[key]) continue;
        seen[key] = true;
        out.push(item);
    }
    return out;
}
function mediaType(url) {
    var value = text(url).toLowerCase();
    if (value.indexOf('.m3u8') >= 0) return 'm3u8';
    if (value.indexOf('.mp4') >= 0) return 'mp4';
    if (value.indexOf('.flv') >= 0) return 'flv';
    return 'auto';
}
function normalizedMediaType(value, url) {
    value = trim(value).toLowerCase();
    if (value === 'm3u8' || value === 'mp4' || value === 'flv' || value === 'auto') return value;
    if (value === 'hls' || value.indexOf('mpegurl') >= 0) return 'm3u8';
    if (value.indexOf('mp4') >= 0) return 'mp4';
    if (value.indexOf('flv') >= 0) return 'flv';
    return mediaType(url);
}
function animeText(value) { return /动漫|动画|番剧|少儿|国漫|日漫|comic|anime/i.test(text(value)); }
function itemType(value, fallback) {
    value = value || {};
    var names = [], groups = [value.res_categories, value.types, value.categorys];
    for (var g = 0; g < groups.length; g++) {
        var list = groups[g] instanceof Array ? groups[g] : [];
        for (var i = 0; i < list.length; i++) {
            var name = typeof list[i] === 'object' ? (list[i].name || list[i].type_name) : list[i];
            if (name && names.indexOf(clean(name)) < 0) names.push(clean(name));
        }
    }
    var base = value.typeName || value.type_name || value.category || value.type || fallback || '';
    var type = clean(names.length ? names.join(',') : base);
    return type;
}
function yearValue(value) {
    value = value || {};
    var year = value.year || value.vod_year || '';
    if (!year && value.years && value.years.length) year = value.years[0].year || value.years[0].name || '';
    return text(year);
}
function imageUrl(value) {
    var url = trim(value);
    if (!url) return '';
    if (/^https?:\/\//i.test(url)) return url;
    if (ADAPTER === 'jianpian') return text(cfg('imageHost', 'https://img.ztwhy.com')).replace(/\/+$/, '') + '/' + url.replace(/^\/+/, '');
    return url;
}
function mapCard(value, fallbackType) {
    value = value || {};
    var id = ADAPTER === 'jianpian' && value.jump_id != null ? value.jump_id : value.id;
    if (id == null) id = value.videoId;
    if (id == null) id = value.vod_id;
    var name = value.name || value.videoName || value.vod_name || value.title || '';
    var pic = value.pic || value.fengmiantu || value.thumbnail || value.path || value.vod_pic || value.tvimg || '';
    var remarks = value.remarks || value.serialDesc || value.newchapter || value.mask || value.vod_remarks || '';
    var card = {
        id: text(id), name: clean(name), pic: imageUrl(pic),
        type: itemType(value, fallbackType), year: yearValue(value), remarks: clean(remarks)
    };
    if (!card.id || !card.name) return null;
    return card;
}
function mapCards(values, fallbackType) {
    var out = [], list = values instanceof Array ? values : [];
    for (var i = 0; i < list.length; i++) {
        var card = mapCard(list[i], fallbackType);
        if (!card) continue;
        if (ANIME_ONLY && card.type && !animeText(card.type)) continue;
        out.push(card);
    }
    return unique(out, 100);
}

// ----- App3Q / NiuLai encrypted prepare -> target -> consume bridge -----
var APP3Q_CRYPTO = {
    key: 'XyeDA1uF8x3WcIeE', iv: 'ohkb6oSM7yyZKZzo',
    access: 'FGAjpziyjdOV',
    accessValue: '27f682b57aaf58c78e8c09cd22b34e324919470b25958322'
};
var NIULAI_CRYPTO = {
    key: 'R7uK3mP9xV2bN5qL', iv: 'T4gH8jS1dF6aZ0cW',
    access: 'NlBridgeAccess',
    accessValue: 'cfe5cf91398c417e42c1d57c09804244903833e63b3aff7f'
};
function bridgeEncrypt(payload, cryptoCfg) {
    var wrapped = {};
    wrapped[cryptoCfg.access] = cryptoCfg.accessValue;
    payload = payload || {};
    for (var key in payload) if (Object.prototype.hasOwnProperty.call(payload, key)) wrapped[key] = payload[key];
    try {
        return text(crypto.aes.encrypt(JSON.stringify(wrapped), cryptoCfg.key, {
            mode: 'CBC', padding: 'PKCS5', keyFormat: 'utf8',
            iv: cryptoCfg.iv, ivFormat: 'utf8', input: 'utf8', output: 'base64'
        })).replace(/=+$/, '');
    } catch (ignore) { return ''; }
}
function bridgeDecrypt(value, cryptoCfg) {
    try {
        var plain = crypto.aes.decrypt(text(value), cryptoCfg.key, {
            mode: 'CBC', padding: 'PKCS5', keyFormat: 'utf8',
            iv: cryptoCfg.iv, ivFormat: 'utf8', input: 'base64', output: 'utf8'
        });
        return parse(plain) || {};
    } catch (ignore) { return {}; }
}
function bridgePost(url, payload, cryptoCfg) {
    var encrypted = bridgeEncrypt(payload, cryptoCfg);
    if (!encrypted) return {};
    var raw = postRaw(url, JSON.stringify({ moyufucking: encrypted }), {
        'Content-Type': 'application/json; charset=utf-8', 'Accept': 'application/json'
    });
    var envelope = parse(raw) || {};
    return bridgeDecrypt(envelope.moyufucking, cryptoCfg);
}
function executeTarget(spec) {
    spec = spec || {};
    var method = text(spec.method || 'GET').toUpperCase();
    var headers = spec.headers || {};
    var body = spec.body_b64 ? b64Decode(spec.body_b64) : text(spec.body || '');
    try {
        /* request2/post2 are the documented way to preserve the target HTTP status for bridge consume. */
        if (typeof http === 'object' && http) {
            var options = { headers: headers, timeout: TIMEOUT };
            var wire = method === 'POST' ? http.post2(spec.url, body, options) : http.request2(spec.url, options);
            return { status: Number(wire && wire.status) || 599, body: method === 'HEAD' ? '' : responseText(wire && wire.body) };
        }
        if (method === 'POST') return { status: 200, body: postRaw(spec.url, body, headers) };
        if (method === 'HEAD') { getRaw(spec.url, headers); return { status: 200, body: '' }; }
        return { status: 200, body: getRaw(spec.url, headers) };
    } catch (ignore) { return { status: 599, body: '' }; }
}
function app3qCall(scene, params) {
    var device = persistentId('fish_app3q_' + SITE_CODE + '_device');
    var prepared = bridgePost(BRIDGE_URL, {
        action: 'prepare', scene: text(scene), params: params || {},
        client_time_ms: Date.now(), device_id: device, state: ''
    }, APP3Q_CRYPTO);
    var data = prepared.data || {};
    if (!prepared.ok || !data.request || !data.ticket) return {};
    var target = executeTarget(data.request);
    var consumed = bridgePost(BRIDGE_URL, {
        action: 'consume', scene: text(scene), ticket: data.ticket,
        status: target.status, body: b64Encode(target.body)
    }, APP3Q_CRYPTO);
    return consumed.ok && consumed.data ? (consumed.data.result || {}) : {};
}
function niulaiCall(scene, params) {
    var device = persistentId('fish_niulai_' + SITE_CODE + '_device');
    var hardware = persistentId('fish_niulai_' + SITE_CODE + '_hardware');
    var state = '';
    for (var round = 0; round < 48; round++) {
        var prepared = bridgePost(BRIDGE_URL, {
            action: 'prepare', site: SITE_CODE, scene: text(scene), params: params || {},
            state: state, device_id: device, hardware_id: hardware
        }, NIULAI_CRYPTO);
        var data = prepared.data || {};
        if (!prepared.ok || !data.request || !data.ticket) return {};
        var target = executeTarget(data.request);
        var consumed = bridgePost(BRIDGE_URL, {
            action: 'consume', site: SITE_CODE, scene: text(scene), ticket: data.ticket,
            status: target.status, body: b64Encode(target.body), state: data.state || state
        }, NIULAI_CRYPTO);
        var next = consumed.data || {};
        if (!consumed.ok) return {};
        if (!next.next) return next.result || {};
        state = text(next.state || state);
    }
    return {};
}

// ----- FuYun -----
var FY_PKG = 'com.baiyunvideo.app';
var FY_KEY = text(cfg('key', 'qvn1u7FCfu8uaolp980i8uVHVS8Dxih7'));
var FY_HOST = text(cfg('host', 'https://js.trgfd.cn')).replace(/\/+$/, '');
var FY_VERSION = text(cfg('version', '2.7.0'));
var FY_UA = text(cfg('ua', 'okhttp/4.12.0'));
var FY_CHANNELS = ['剧集', '电影', '综艺', '动漫', '少儿', '纪录片'];
function fuyunJson(url, headers) { return parse(getRaw(url, headers || { 'User-Agent': FY_UA })); }
function fuyunDecrypt(value) {
    try {
        var hex = crypto.base64.decode(trim(value), { output: 'hex' }) || '';
        if (hex.length < 56) return '';
        return text(crypto.aes.decrypt(hex.substring(24), FY_KEY, {
            mode: 'GCM', padding: 'NoPadding', keyFormat: 'utf8',
            iv: hex.substring(0, 24), ivFormat: 'hex', input: 'hex', output: 'utf8', tagLen: 128
        }));
    } catch (ignore) { return ''; }
}
function fuyunCategory(channel, page, filters) {
    channel = text(channel || (ANIME_ONLY ? '动漫' : '剧集'));
    filters = filters || {};
    var middle = channel === '少儿'
        ? ['全部', '全部', '全部', '全部', '全部']
        : ['全部', filters.area || '全部', filters.year || '全部'];
    var segments = [FY_HOST, 'cache', 'zhaopian', encode(channel)];
    for (var i = 0; i < middle.length; i++) segments.push(encode(middle[i]));
    segments.push(encode(filters.sort || '最新'));
    segments.push(text(page || 1) + '.json');
    var list = fuyunJson(segments.join('/')) || [];
    return mapCards(list, channel);
}
function fuyunDetail(id) {
    var dir = Math.floor((parseInt(id, 10) || 0) / 1000);
    var url = FY_HOST + '/cache/videos/' + dir + '/' + encode(id) + '.json?version=' + encode(FY_VERSION) +
        '&baoming=' + FY_PKG + '&channel=fenxiang';
    var plain = fuyunDecrypt(getRaw(url, { 'User-Agent': FY_UA }));
    var value = parse(plain) || {};
    var out = {
        id: text(id), name: clean(value.videoName), pic: imageUrl(value.fengmiantu || value.dahengtu || ''),
        desc: clean(value.blurb || value.shortBlurb || ''), type: clean(value.typeName || value['class'] || ''),
        year: text(value.year || ''), remarks: clean(value.remarks || value.serialDesc || ''), episodes: []
    };
    var episodes = value.playUrlList instanceof Array ? value.playUrlList : [];
    for (var i = 0; i < episodes.length; i++) {
        var ep = episodes[i] || {};
        if (ep.ji == null) continue;
        out.episodes.push({ name: clean(ep.name) || ('第' + (i + 1) + '集'), url: 'fy|' + id + '|' + ep.ji + '|' + i });
    }
    return out;
}
function fuyunPlay(flag) {
    var parts = text(flag).split('|');
    if (parts.length < 4) return { url: '', type: 'auto' };
    var id = parts[1], ji = parts[2], index = parts[3];
    var chars = 'abcdefghijklmnopqrstuvwxyz0123456789', androidId = '';
    for (var i = 0; i < 16; i++) androidId += chars.charAt(Math.floor(Math.random() * chars.length));
    var url = FY_HOST + '/vc/api/video/playurl?sid=' + encode(id) + '&ji=' + encode(ji) + '&jiIndex=' + encode(index) +
        '&t=0&y=0&isjiid=1&androidId=' + androidId + '&version=' + encode(FY_VERSION) +
        '&baoming=' + FY_PKG + '&channel=fenxiang';
    var signature = '';
    try { signature = text(md5(id + FY_KEY)); } catch (ignore) {}
    var result = fuyunJson(url, { 'User-Agent': FY_UA, 'vuk': signature }) || {};
    var direct = result.data && result.data.url ? text(result.data.url) : '';
    return { url: direct, type: mediaType(direct), headers: { 'User-Agent': FY_UA } };
}

// ----- Jianpian -----
var JP_HOSTS = (function () {
    var raw = text(cfg('hosts', 'https://wangerniu.shmjnd.com,https://wangerniu.dazidu.com,https://wangerniu.whfft.com,https://wangerniu.zxfmj.com,https://ev5356.970xw.com'));
    var out = [], parts = raw.split(',');
    for (var i = 0; i < parts.length; i++) if (trim(parts[i])) out.push(trim(parts[i]).replace(/\/+$/, ''));
    return out;
})();
var JP_UA = text(cfg('jpUa', 'jianpian-android/350'));
var JP_AUTH = text(cfg('jpAuth', 'y261ow7kF2dtzlxh1GS9EB8nbTxNmaK/QQIAjctlKiEv'));
var _jpHostIndex = 0;
function jpHeaders() { return { 'User-Agent': JP_UA, 'JPAUTH': JP_AUTH, 'Accept': 'application/json' }; }
function jpGet(path) {
    for (var offset = 0; offset < JP_HOSTS.length; offset++) {
        var index = (_jpHostIndex + offset) % JP_HOSTS.length;
        var result = parse(getRaw(JP_HOSTS[index] + path, jpHeaders()));
        if (result && (result.code == null || Number(result.code) === 1 || Number(result.code) === 200)) {
            _jpHostIndex = index;
            return result;
        }
    }
    return {};
}
function jpList(path, fallbackType) {
    var result = jpGet(path);
    var data = result.data instanceof Array ? result.data : (result.data && result.data.list instanceof Array ? result.data.list : []);
    return mapCards(data, fallbackType);
}
function personNames(values) {
    var out = [], list = values instanceof Array ? values : [];
    for (var i = 0; i < list.length; i++) {
        var value = list[i];
        var name = typeof value === 'object' ? value.name : value;
        if (name) out.push(clean(name));
    }
    return out.join(' / ');
}
function jianpianDetail(id) {
    var root = jpGet('/api/video/detailv2?id=' + encode(id));
    var value = root.data || {};
    var out = {
        id: text(id), name: clean(value.title), pic: imageUrl(value.thumbnail || value.path || ''),
        desc: clean(value.description || ''), type: clean(value.type || (value.types && value.types[0] && value.types[0].name) || ''),
        year: text(value.year || ''), remarks: clean(value.mask || value.score || ''),
        actor: personNames(value.actors), director: personNames(value.directors), episodes: []
    };
    var groups = value.source_list_source instanceof Array && value.source_list_source.length
        ? value.source_list_source : value.vip_source_list_source;
    groups = groups instanceof Array ? groups : [];
    for (var i = 0; i < groups.length; i++) {
        var group = groups[i] || {}, entries = group.source_list instanceof Array ? group.source_list : [];
        for (var j = 0; j < entries.length; j++) {
            var ep = entries[j] || {}, direct = trim(ep.url);
            if (!/^https?:\/\//i.test(direct)) continue;
            out.episodes.push({
                name: clean(ep.source_name || ep.title || ep.weight) || ('第' + (j + 1) + '集'),
                route: clean(group.name || ep.source_config_name || '荐片'), url: direct
            });
        }
    }
    if (!out.episodes.length) {
        var directGroups = [value.m3u8_list, value.ftp_list];
        for (var g = 0; g < directGroups.length; g++) {
            var entries2 = directGroups[g] instanceof Array ? directGroups[g] : [];
            for (var k = 0; k < entries2.length; k++) {
                var ep2 = entries2[k] || {}, direct2 = trim(ep2.url);
                if (!/^https?:\/\//i.test(direct2)) continue;
                out.episodes.push({ name: clean(ep2.title) || ('第' + (k + 1) + '集'), route: '荐片', url: direct2 });
            }
        }
    }
    return out;
}

// ----- Common adapter -----
var _homeData = null;
var _detailCache = {};
function adapterHome() {
    if (_homeData) return _homeData;
    var result = {};
    if (ADAPTER === 'app3q') result = app3qCall('home', {});
    else if (ADAPTER === 'niulai') result = niulaiCall('home', { filter: true, sdk: SDK_INT });
    else if (ADAPTER === 'fuyun') {
        result.classes = [];
        for (var i = 0; i < FY_CHANNELS.length; i++) result.classes.push({ id: FY_CHANNELS[i], name: FY_CHANNELS[i] });
        result.list = fuyunCategory(ANIME_ONLY ? '动漫' : '剧集', 1, { sort: '最新' });
    } else if (ADAPTER === 'jianpian') {
        var categoriesRoot = jpGet('/api/v2/settings/homeCategory');
        result.classes = categoriesRoot.data instanceof Array ? categoriesRoot.data : [];
        result.list = jpList('/api/slide/list?pos_id=88', ANIME_ONLY ? '动漫' : '影视');
    }
    _homeData = result && typeof result === 'object' ? result : {};
    return _homeData;
}
function classList() {
    var values = adapterHome().classes;
    values = values instanceof Array ? values : [];
    var out = [];
    for (var i = 0; i < values.length; i++) {
        var value = values[i] || {};
        var id = value.id != null ? value.id : value.type_id;
        var name = value.name || value.type_name || value.title || '';
        if (id == null || !name) continue;
        if (ANIME_ONLY && !animeText(name) && !animeText(id)) continue;
        out.push({ id: text(id), name: clean(name) });
    }
    if (ANIME_ONLY && !out.length) {
        if (ADAPTER === 'jianpian') out.push({ id: '3', name: '动漫' });
        else if (ADAPTER === 'fuyun') out.push({ id: '动漫', name: '动漫' }, { id: '少儿', name: '少儿' });
        else out.push({ id: 'comic', name: '动漫' });
    }
    return out;
}
function adapterCategory(category, page, filters) {
    category = text(category);
    page = Math.max(1, Number(page) || 1);
    filters = filters || {};
    if (ADAPTER === 'app3q') return mapCards((app3qCall('category', { tid: category, page: page }).list || []), category);
    if (ADAPTER === 'niulai') {
        return mapCards((niulaiCall('category', { tid: category, page: page, extend: filters, sdk: SDK_INT }).list || []), category);
    }
    if (ADAPTER === 'fuyun') return fuyunCategory(category, page, filters);
    if (ADAPTER === 'jianpian') {
        if (category === '50' || category === '99' || category === '111') {
            return jpList('/api/dyTag/list?category_id=' + encode(category) + '&page=' + page, category);
        }
        var path = '/api/crumb/list?fcate_pid=' + encode(category) + '&area=' + encode(filters.area || '') +
            '&year=' + encode(filters.year || '') + '&type=0&sort=' + encode(filters.sort || 'updata') +
            '&page=' + page + '&category_id=' + encode(category);
        return jpList(path, category === '3' ? '动漫' : '影视');
    }
    return [];
}
function adapterSearch(keyword, page) {
    keyword = trim(keyword);
    page = Math.max(1, Number(page) || 1);
    if (!keyword) {
        var classes = classList();
        return classes.length ? adapterCategory(classes[0].id, page, {}) : mapCards(adapterHome().list || []);
    }
    if (ADAPTER === 'app3q') return mapCards((app3qCall('search', { key: keyword, page: page }).list || []));
    if (ADAPTER === 'niulai') return mapCards((niulaiCall('search', { keyword: keyword, page: page, sdk: SDK_INT }).list || []));
    if (ADAPTER === 'fuyun') {
        return mapCards(fuyunJson(FY_HOST + '/vc/api/search/' + encode(keyword) + '/' + page + '.json') || []);
    }
    if (ADAPTER === 'jianpian') {
        return jpList('/api/v2/search/videoV2?key=' + encode(keyword) + '&category_id=88&page=' + page + '&pageSize=20');
    }
    return [];
}
function adapterDetail(id) {
    var key = text(id);
    if (_detailCache[key]) return _detailCache[key];
    var result = {};
    if (ADAPTER === 'app3q') result = app3qCall('detail', { id: key });
    else if (ADAPTER === 'niulai') result = niulaiCall('detail', { id: key, sdk: SDK_INT });
    else if (ADAPTER === 'fuyun') result = fuyunDetail(key);
    else if (ADAPTER === 'jianpian') result = jianpianDetail(key);
    if (ADAPTER === 'app3q' || ADAPTER === 'niulai') {
        var vod = result.vod || {};
        var out = {
            id: text(vod.id != null ? vod.id : key), name: clean(vod.name), pic: imageUrl(vod.pic || ''),
            desc: clean(vod.content || vod.desc || ''), type: clean(vod.type || ''), year: text(vod.year || ''),
            remarks: clean(vod.remarks || ''), actor: clean(vod.actor || ''), director: clean(vod.director || ''), episodes: []
        };
        var sources = result.sources instanceof Array ? result.sources : [];
        for (var i = 0; i < sources.length; i++) {
            var source = sources[i] || {}, episodes = source.episodes instanceof Array ? source.episodes : [];
            for (var j = 0; j < episodes.length; j++) {
                var ep = episodes[j] || {}, meta;
                if (ADAPTER === 'app3q') meta = { adapter: 'app3q', play_id: ep.play_id };
                else meta = {
                    adapter: 'niulai', flag: text(source.name), url: text(ep.url != null ? ep.url : ep.play_id),
                    line: text(ep.line || source.name),
                    title: text(ep.name), vodname: text(vod.name), sdk: SDK_INT, force_session: false
                };
                out.episodes.push({
                    name: clean(ep.name) || ('第' + (j + 1) + '集'), route: clean(source.name || ('线路' + (i + 1))),
                    url: 'bridge|' + b64Encode(JSON.stringify(meta))
                });
            }
        }
        result = out;
    }
    _detailCache[key] = result;
    return result;
}
function adapterPlay(flag) {
    flag = text(flag);
    if (ADAPTER === 'fuyun') return fuyunPlay(flag);
    if (ADAPTER === 'jianpian') return { url: flag, type: mediaType(flag), headers: jpHeaders() };
    if (flag.indexOf('bridge|') !== 0) return { url: '', type: 'auto' };
    var meta = parse(b64Decode(flag.substring(7))) || {};
    var result = meta.adapter === 'app3q'
        ? app3qCall('play', { play_id: meta.play_id })
        : niulaiCall('player', {
            flag: meta.flag, url: meta.url, line: meta.line, title: meta.title,
            vodname: meta.vodname, sdk: meta.sdk || SDK_INT, force_session: !!meta.force_session
        });
    if (meta.adapter === 'niulai' && !(result && (result.url || result.play_url))) {
        result = niulaiCall('player', {
            flag: meta.flag, url: meta.url, line: meta.line, title: meta.title,
            vodname: meta.vodname, sdk: meta.sdk || SDK_INT, force_session: true
        });
    }
    var direct = text(result.url || result.play_url || '');
    return { url: direct, type: normalizedMediaType(result.type, direct), headers: result.header || result.headers || {} };
}

function config() {
    return JSON.stringify({ kind: 'video', browseOnly: false, source: SOURCE_NAME, animeOnly: ANIME_ONLY });
}
function filterSet() {
    return [
        { key: 'sort', name: '排序', value: [
            { n: '最新', v: ADAPTER === 'fuyun' ? '最新' : 'updata' },
            { n: '最热', v: ADAPTER === 'fuyun' ? '最热' : 'hits' },
            { n: '高分', v: ADAPTER === 'fuyun' ? '评分' : 'score' }
        ] },
        { key: 'year', name: '年份', value: [
            { n: '全部', v: '' }, { n: '2026', v: '2026' },
            { n: '2025', v: '2025' }, { n: '2024', v: '2024' }, { n: '2023', v: '2023' },
            { n: '2022', v: '2022' }, { n: '2021', v: '2021' }, { n: '2020', v: '2020' }
        ] }
    ];
}
function categories() {
    try {
        var out = [{ key: '', title: '推荐' }], classes = classList();
        for (var i = 0; i < classes.length; i++) {
            var item = { key: classes[i].id, title: classes[i].name };
            /* App3Q has no proven filter parameters; do not advertise filters that searchFiltered cannot apply. */
            if (ADAPTER !== 'app3q') item.filters = filterSet();
            out.push(item);
        }
        return JSON.stringify(out);
    } catch (ignore) { return JSON.stringify([{ key: '', title: '推荐' }]); }
}
function homeSections() {
    try {
        var out = [], home = adapterHome(), cards = mapCards(home.list || [], ANIME_ONLY ? '动漫' : '影视');
        if (cards.length) out.push({ title: SOURCE_NAME + (ANIME_ONLY ? '动漫推荐' : '首页推荐'), key: '__hero__', items: cards.slice(0, 12) });
        var classes = classList(), max = ANIME_ONLY ? Math.min(2, classes.length) : Math.min(3, classes.length);
        for (var i = 0; i < max; i++) {
            var list = adapterCategory(classes[i].id, 1, {});
            if (list.length) out.push({ title: SOURCE_NAME + ' · ' + classes[i].name, key: classes[i].id, items: list.slice(0, 12) });
        }
        if (!out.length && cards.length) out.push({ title: SOURCE_NAME, key: '', items: cards });
        return JSON.stringify(out);
    } catch (ignore) { return '[]'; }
}
function search(keyword, page) {
    try {
        var key = trim(keyword), classes = key ? classList() : [];
        for (var i = 0; i < classes.length; i++) {
            if (text(classes[i].id) === key) return JSON.stringify(adapterCategory(key, page, {}));
        }
        return JSON.stringify(adapterSearch(key, page));
    } catch (ignore) { return '[]'; }
}
function searchFiltered(category, filtersJson, page) {
    try { return JSON.stringify(adapterCategory(category, page, parse(filtersJson) || {})); } catch (ignore) { return '[]'; }
}
function detail(id) {
    try {
        var value = adapterDetail(id) || {};
        if (!value.episodes) value.episodes = [];
        return JSON.stringify(value);
    } catch (ignore) { return JSON.stringify({ id: text(id), name: '', pic: '', desc: '', episodes: [] }); }
}
function play(flag) {
    try { return JSON.stringify(adapterPlay(flag)); } catch (ignore) { return JSON.stringify({ url: '', type: 'auto' }); }
}
function related(id) {
    try {
        var value = adapterDetail(id) || {};
        return JSON.stringify(value.name ? adapterSearch(value.name, 1).filter(function (item) { return text(item.id) !== text(id); }).slice(0, 12) : []);
    } catch (ignore) { return '[]'; }
}
// ===== drpy 适配层: 易看源 -> drpy0(TVBox/FongMi) 约定 =====
// 注意: drpy 函数一律用 drpy_ 前缀, 避免覆盖易看源的同名函数(hoisting 后者会赢)
function __ekCards(a) {
    a = (typeof a === 'string') ? JSON.parse(a || '[]') : (a || []);
    if (!Array.isArray(a)) a = [];
    return a.map(function (x) {
        return { vod_id: String(x.id || ''), vod_name: String(x.name || ''), vod_pic: String(x.pic || ''),
                 vod_remarks: String(x.remarks || ''), vod_year: String(x.year || ''),
                 vod_class: String(x.type || ''), vod_content: String(x.desc || '') };
    });
}
function __ekExtApply(cfg) {
    try {
        if (cfg && cfg.ext) {
            var o = (typeof cfg.ext === 'string') ? JSON.parse(cfg.ext) : cfg.ext;
            if (o && typeof o === 'object') for (var k in o) __ek_ext[k] = o[k];
        }
    } catch (e) {}
}
function drpy_init(cfg) { __ekExtApply(cfg); }
function drpy_home(filter) {
    var classes = [], filters = {};
    try {
        var cats = JSON.parse(categories());
        cats.forEach(function (c) {
            if (c.key === '' || c.key == null) return;
            classes.push({ type_id: String(c.key), type_name: String(c.title || c.key) });
            if (c.filters && c.filters.length) filters[String(c.key)] = c.filters;
        });
    } catch (e) {}
    return JSON.stringify({ class: classes, filters: filters });
}
function drpy_homeVod() {
    try {
        if (typeof homeSections === 'function') {
            var secs = JSON.parse(homeSections());
            var cards = [];
            (Array.isArray(secs) ? secs : []).forEach(function (s) { (s.cards || s.list || []).forEach(function (c) { cards.push(c); }); });
            return JSON.stringify({ list: __ekCards(JSON.stringify(cards)) });
        }
    } catch (e) {}
    return JSON.stringify({ list: [] });
}
function drpy_category(tid, pg, filter, extend) {
    pg = Math.max(1, parseInt(pg, 10) || 1);
    try {
        var f = {};
        try { f = (typeof extend === 'string' && extend) ? JSON.parse(extend) : (extend || {}); } catch (e) {}
        if (typeof searchFiltered === 'function' && tid) return JSON.stringify({ page: pg, pagecount: 9999, list: __ekCards(searchFiltered(String(tid), JSON.stringify(f), pg)) });
        if (typeof search === 'function') return JSON.stringify({ page: pg, pagecount: 9999, list: __ekCards(search('', pg)) });
    } catch (e) {}
    return JSON.stringify({ page: pg, pagecount: 9999, list: [] });
}
function drpy_detail(id) {
    try {
        var d = JSON.parse(detail(String(id)));
        var groups = {}, order = [];
        (d.episodes || []).forEach(function (e) {
            var rt = String(e.route || 'source');
            if (!groups[rt]) { groups[rt] = []; order.push(rt); }
            groups[rt].push(String(e.name || '') + '$' + String(e.url || ''));
        });
        var v = { vod_id: String(d.id || id), vod_name: String(d.name || ''), vod_pic: String(d.pic || ''),
                  vod_content: String(d.desc || ''), vod_year: String(d.year || ''), vod_area: String(d.area || ''),
                  vod_actor: String(d.actor || ''), vod_director: String(d.director || ''), vod_class: String(d.type || ''),
                  vod_play_from: order.join('$$$'), vod_play_url: order.map(function (k) { return groups[k].join('#'); }).join('$$$') };
        return JSON.stringify({ list: [v] });
    } catch (e) { return JSON.stringify({ list: [] }); }
}
function drpy_search(wd, quick, pg) {
    pg = Math.max(1, parseInt(pg, 10) || 1);
    try {
        if (typeof search === 'function') return JSON.stringify({ list: __ekCards(search(String(wd || ''), pg)) });
    } catch (e) {}
    return JSON.stringify({ list: [] });
}
function drpy_play(flag, id, flags) {
    try {
        var r = JSON.parse(play(String(id)));
        var u = String(r.url || '');
        if (!u) return JSON.stringify({ parse: 0, url: '' });
        var out = { parse: 0, url: u };
        var hd = r.headers || r.header;
        if (hd && typeof hd === 'string') { try { hd = JSON.parse(hd); } catch (e) { hd = undefined; } }
        if (hd && typeof hd === 'object' && Object.keys(hd).length) out.header = hd;
        return JSON.stringify(out);
    } catch (e) { return JSON.stringify({ parse: 0, url: '' }); }
}
function __jsEvalReturn() {
    return { init: drpy_init, home: drpy_home, homeVod: drpy_homeVod, category: drpy_category,
             detail: drpy_detail, search: drpy_search, play: drpy_play };
}
// ===== 适配层结束 =====
